project:
  title: "math-garden"
  type: website

website:
  title: "M's Archives"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: rough-notes.qmd
        text: Rough Notes

      - text: Refined Notes
        menu:
          - href: refined-notes/navigation-pages/math-logic.qmd
            text: Mathematical Logic

format:
  html:
    html-math-method: mathjax
    include-in-header:
      - latex-setup/macros.html
    theme:
      - darkly
      - styles.scss

callout-appearance: minimal