project:
  title: "math-garden"
  type: website

website:
  title: "M's Archives"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rough-notes
        text: Rough Notes
      - href: refined-notes
        text: Refined Notes

format:
  html:
    html-math-method: mathjax
    include-in-header:
      - latex-setup/commands.html
