project:
  title: "math-garden"
  type: website

website:
  title: "M's Archives"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: refined-notes/functions.qmd
        text: Functions

format:
  html:
    html-math-method: mathml
    include-in-header: latex-setup/preamble.tex

extensions:
  - latex-setup/preamble.tex


