---
title: Welcome to my Digital Garden
---

## Layout

There are two large sections; [Rough Notes](./rough-notes.qmd) and [Refined Notes](./refined-notes.qmd).

The [Rough Notes](./rough-notes.qmd) folder will contain first draft notes/rough work just to be able to organize everything later. These will be messy so be warned.

The [Refined Notes](./refined-notes.qmd) folder will contain pages that are fully organized, with links between pages so that it's easier to see connections and also refer back to any theorems/results. If you're not sure where to start, I recommend starting here and look at some of the "Navigation pages" listed there.

The [Resources](./resources.qmd) page is just a list of math-related resources that I want to store. I may not have necessarily read all of them, nor have I necessarily used them to create this wiki. Feel free to take a look at those for your next math read!

## About me

Hello! I go by M, I recently graduated with a BSc in Pure Math, and I hope to go to graduate school to eventually become a professor in an Algebra-related field.

I decided to build this math wiki (of sorts) so I can prepare myself for a Master's while I take a break from school to save up some money. The biggest struggle I had in undergraduate was how interconnected mathematics is, and I needed a big wiki for myself so I could see these connections + for organization purposes, but never had the time. I'm hoping this wiki is of use for others on their mathematical journey! I'll be adding to this wiki constantly so stay tuned :))

Feel free to contact me via any of the following;

- email: [msarchives314@gmail.com](mailto:msarchives314@gmail.com)
- Instagram: [@msarchives314](https://www.instagram.com/msarchives314/)
- X: [@ms_archives314](https://x.com/ms_archives314)

## Disclaimers and Regulation
- I am open to constructive feedback! If you find any of the following please feel free to contact me and I will edit the wiki to the best of my ability;
	- Errors - not everything is 100% accurate
	- Inconsistencies in analogies, interpretations, generalizations - a lot of those will be personal so there may be caveats or might just not work at all
	- Poor formatting/layout - if pages feel disorganized please tell me how you would like to see it improved
- Do not claim this work as your own - I have put a lot of time and effort into creating this, examples of this include but are not limited to;
	- Academic dishonesty - using proofs or answers to examples or other in assignments, papers, etc
		- This resembles a blog more than anything! Please don't use this as a citation unless you are given permission or you think it is appropriate
	- Claiming to be the creator on any platform or in real life